name: CodeFundi Build Diagnosis AI
description: Automatically capture and diagnose errors in your GitHub Action logs.
author: CodeFundi
branding:
  icon: zap
  color: blue
inputs:
  command:
    description: 'The npm command you want to run (e.g., "npm run build").'
    required: true
    default: "npm run build"
  key:
    description: >-
      The Code Fundi API key. Learn more:
      https://docs.codefundi.app/docs/features/frontend_debug#setup-api-key
    required: true
    default: ''
  silent:
    description: Runs CodeFundi in silent mode if true.
    required: false
    default: 'false'
    type: boolean
runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Run npm command and handle errors
      id: run-command
      shell: bash
      run: |
        set +e
        
        # Run the npm command
        ERROR_LOG=$(eval "${{ inputs.command }}" 2>&1)
        EXIT_CODE=$?
        
        if [ $EXIT_CODE -ne 0 ]; then
          echo "🚫 Command failed with exit code $EXIT_CODE. Running diagnosis..."
          
          SILENT_FLAG=""
          if [ "${{ inputs.silent }}" = "true" ]; then
            SILENT_FLAG="-s"
          fi

          # Run CodeFundi diagnosis and log its output for debugging
          echo "Running CodeFundi diagnosis..."
          DIAGNOSIS_OUTPUT=$(npx --yes @codefundi/cli --key="${{ inputs.key }}" --chat "$ERROR_LOG" -r $SILENT_FLAG 2>&1)
          DIAGNOSIS_EXIT_CODE=$?

          echo "$DIAGNOSIS_OUTPUT"

          if [ $DIAGNOSIS_EXIT_CODE -ne 0 ]; then
            echo "❗ Diagnosis command failed with exit code $DIAGNOSIS_EXIT_CODE."
          else
            echo "🔍 Diagnosis completed successfully."
          fi
        else
          echo "✅ Command ran successfully."
        fi

        set -e