name: CodeFundi Build Diagnosis AI
description: Automatically capture and diagnose errors in your GitHub Action logs.
author: CodeFundi
branding:
  icon: zap
  color: blue
inputs:
  command:
    description: 'The command you want to run (e.g., "npm run build").'
    required: true
    default: "npm run build"
  key:
    description: >-
      The Code Fundi API key. Learn more:
      https://docs.codefundi.app/docs/features/frontend_debug#setup-api-key
    required: true
    default: ''
runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Run command and handle errors
      id: run-command
      shell: bash
      run: |
        set +e
        
        # Run the command
        ERROR_LOG=$(eval "${{ inputs.command }}" 2>&1)
        EXIT_CODE=$?
        
        if [ $EXIT_CODE -ne 0 ]; then
          echo "Running CodeFundi diagnosis..."
          DIAGNOSIS_OUTPUT=$(npx --yes @codefundi/cli --key="${{ inputs.key }}" --diagnose "$ERROR_LOG" -r -s 2>&1)
          DIAGNOSIS_EXIT_CODE=$?

          # Output diagnosis to GitHub Actions annotations
          if [ $DIAGNOSIS_EXIT_CODE -ne 0 ]; then
            echo "::error::â— Code Fundi Diagnosis command failed with exit code $DIAGNOSIS_EXIT_CODE"
          else
            echo "::notice::ðŸ” Code Fundi Diagnosis completed successfully."

            # Initialize a counter
            count=0
            echo "$DIAGNOSIS_OUTPUT" | while IFS= read -r line; do
              count=$((count + 1))  # Increment the counter
              if [ "$count" -eq 1 ]; then
                echo "# $line" >> $GITHUB_STEP_SUMMARY  # Append # to the first line
              elif [ "$count" -eq 2 ] || [ "$count" -eq 3 ]; then
                echo "" >> $GITHUB_STEP_SUMMARY  # Skip spinner text
              else
                echo "$line" >> $GITHUB_STEP_SUMMARY  # Echo all other lines
              fi
            done
          fi
        else
          echo "::notice::âœ… No errors detected during the Code Fundi Diagnosis."
        fi

        set -e