name: CodeFundi Build Diagnosis AI
description: Automatically capture and diagnose errors in your Github Action logs.
author: CodeFundi
branding:
  icon: zap
  color: blue
inputs:
  command:
    description: 'The npm command you want to run (e.g., "npm run build").'
    required: true
    default: "npm run build"
  key:
    description: >-
      The Code Fundi API key. Learn more:
      https://docs.codefundi.app/docs/features/frontend_debug#setup-api-key
    required: true
    default: ''
  silent:
    description: Runs Code Fundi in silent mode if true.
    required: false
    default: 'false'
    type: boolean
runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Run npm command and handle errors
      id: run-command
      shell: bash
      run: |
        # Run the npm command
        ERROR_LOG=$(eval "${{ inputs.command }}" 2>&1)
        EXIT_CODE=$?

        if [ $EXIT_CODE -ne 0 ]; then
          echo "🚫 Command failed with exit code $EXIT_CODE. Running diagnosis..."
          echo "Error log: $ERROR_LOG"
          
          SILENT_FLAG=""
          if [ "${{ inputs.silent }}" = "true" ]; then
            SILENT_FLAG="-s"
          fi

          npx @codefundi/cli --key="${{ inputs.key }}" --diagnose "$ERROR_LOG" $SILENT_FLAG
          
          echo "error_occurred=true" >> $GITHUB_OUTPUT
        else
          echo "✅ Command ran successfully."
          echo "error_occurred=false" >> $GITHUB_OUTPUT
        fi
        
        # Always exit with 0 to allow GitHub Actions to continue
        exit 0
    - name: Check for errors
      if: steps.run-command.outputs.error_occurred == 'true'
      shell: bash
      run: exit 1