name: CodeFundi Build Diagnosis AI
description: Automatically capture and diagnose errors in your GitHub Action logs.
author: CodeFundi
branding:
  icon: zap
  color: blue
inputs:
  command:
    description: 'The npm command you want to run (e.g., "npm run build").'
    required: true
    default: "npm run build"
  key:
    description: >-
      The Code Fundi API key. Learn more:
      https://docs.codefundi.app/docs/features/frontend_debug#setup-api-key
    required: true
    default: ''
  silent:
    description: Runs CodeFundi in silent mode if true.
    required: false
    default: 'false'
    type: boolean
runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Run npm command and capture errors
      id: run-command
      run: |
        set +e
        ERROR_LOG=$(eval "${{ inputs.command }}" 2>&1)
        echo "$ERROR_LOG" > error_log.txt
        echo "::set-output name=exit-code::$?"
        set -e

    - name: Check if the command failed
      id: check-failure
      run: |
        if [ "${{ steps.run-command.outputs.exit-code }}" -ne 0 ]; then
          echo "true" > failed.txt
        else
          echo "false" > failed.txt
      continue-on-error: true

    - name: Run CodeFundi Diagnosis if command failed
      if: ${{ steps.check-failure.outputs.failed == 'true' }}
      run: |
        SILENT_FLAG=""
        if [ "${{ inputs.silent }}" = "true" ]; then
          SILENT_FLAG="-s"
        fi
        npx --yes @codefundi/cli --key="${{ inputs.key }}" --diagnose "$(cat error_log.txt)" $SILENT_FLAG
